<?php

use App\UrlShortener\Url\Interface\IUrlShortener;

class UrlShortenerTest extends TestCase
{
    private IUrlShortener $urlShortenerObj;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->urlShortenerObj = app()->make(IUrlShortener::class);
    }

    /** @test */
    public function can_generate_url_key()
    {
        $key = $this->urlShortenerObj->generateKey($id = 1);

        $this->assertNotNull($key);
    }

    /** @test */
    public function can_decode_url_key()
    {
        $id = 1;

        $key = $this->urlShortenerObj->generateKey($id);

        $decodedKey = $this->urlShortenerObj->decodeKey($key);

        $this->assertEquals($id, $decodedKey[0]);
    }
}
